extension anychart.enums {
    public enum EventType: String {
        case ANIMATION_END = "animationEnd"
        case ANIMATION_START = "animationStart"
        case ANNOTATION_CHANGE = "annotationChange"
        case ANNOTATION_CHANGE_FINISH = "annotationChangeFinish"
        case ANNOTATION_CHANGE_START = "annotationChangeStart"
        case ANNOTATION_DRAWING_FINISH = "annotationDrawingFinish"
        case ANNOTATION_SELECT = "annotationSelect"
        case ANNOTATION_UNSELECT = "annotationUnselect"
        case AXIS_MARKER_MOVE = "axisMarkerMove"
        case AXIS_MARKER_OUT = "axisMarkerOut"
        case AXIS_MARKER_OVER = "axisMarkerOver"
        case BEFORE_CREATE_CONNECTOR = "beforeCreateConnector"
        case CHART_DRAW = "chartDraw"
        case CLOSE = "close"
        case COMPLETE = "complete"
        case CONNECTOR_CLICK = "connectorClick"
        case CONNECTOR_DBL_CLICK = "connectorDblclick"
        case CONNECTOR_MOUSE_DOWN = "connectorMouseDown"
        case CONNECTOR_MOUSE_MOVE = "connectorMouseMove"
        case CONNECTOR_MOUSE_OUT = "connectorMouseOut"
        case CONNECTOR_MOUSE_OVER = "connectorMouseOver"
        case CONNECTOR_MOUSE_UP = "connectorMouseUp"
        case CONNECTOR_SELECT = "connectorSelect"
        case DATA_CHANGED = "dataChanged"
        case DRAG = "drag"
        case DRAG_END = "dragEnd"
        case DRAG_START = "dragStart"
        case DRILL_CHANGE = "drillChange"
        case EDITOR_COMPLETE = "editorComplete"
        case EVENT_MARKERS_HOVER = "eventMarkersHover"
        case EVENT_MARKERS_SELECT = "eventMarkersSelect"
        case EVENT_MARKER_CLICK = "eventMarkerClick"
        case EVENT_MARKER_DBLCLICK = "eventMarkerDblClick"
        case EVENT_MARKER_MOUSE_DOWN = "eventMarkerMouseDown"
        case EVENT_MARKER_MOUSE_MOVE = "eventMarkerMouseMove"
        case EVENT_MARKER_MOUSE_OUT = "eventMarkerMouseOut"
        case EVENT_MARKER_MOUSE_OVER = "eventMarkerMouseOver"
        case EVENT_MARKER_MOUSE_UP = "eventMarkerMouseUp"
        case LEGEND_ITEM_CLICK = "legendItemClick"
        case LEGEND_ITEM_DBLCLICK = "legendItemDblclick"
        case LEGEND_ITEM_MOUSE_DOWN = "legendItemMouseDown"
        case LEGEND_ITEM_MOUSE_MOVE = "legendItemMouseMove"
        case LEGEND_ITEM_MOUSE_OUT = "legendItemMouseOut"
        case LEGEND_ITEM_MOUSE_OVER = "legendItemMouseOver"
        case LEGEND_ITEM_MOUSE_UP = "legendItemMouseUp"
        case POINTS_HOVER = "pointsHover"
        case POINTS_SELECT = "pointsSelect"
        case POINT_CLICK = "pointClick"
        case POINT_DBLCLICK = "pointDblclick"
        case POINT_HOVER = "pointHover"
        case POINT_MOUSE_DOWN = "pointMouseDown"
        case POINT_MOUSE_MOVE = "pointMouseMove"
        case POINT_MOUSE_OUT = "pointMouseOut"
        case POINT_MOUSE_OVER = "pointMouseOver"
        case POINT_MOUSE_UP = "pointMouseUp"
        case ROW_CLICK = "rowClick"
        case ROW_DBL_CLICK = "rowDblClick"
        case ROW_MOUSE_DOWN = "rowMouseDown"
        case ROW_MOUSE_MOVE = "rowMouseMove"
        case ROW_MOUSE_OUT = "rowMouseOut"
        case ROW_MOUSE_OVER = "rowMouseOver"
        case ROW_MOUSE_UP = "rowMouseUp"
        case ROW_SELECT = "rowSelect"
        case SCROLLER_CHANGE = "scrollerchange"
        case SCROLLER_CHANGE_FINISH = "scrollerChangeFinish"
        case SCROLLER_CHANGE_START = "scrollerchangestart"
        case SCROLL_CHANGE = "scrollChange"
        case SELECTED_RANGE_BEFORE_CHANGE = "selectedRangeBeforeChange"
        case SELECTED_RANGE_CHANGE = "selectedRangeChange"
        case SELECTED_RANGE_CHANGE_FINISH = "selectedRangeChangeFinish"
        case SELECTED_RANGE_CHANGE_START = "selectedRangeChangeStart"
        case SELECT_MARQUEE_CHANGE = "selectMarqueeChange"
        case SELECT_MARQUEE_FINISH = "selectMarqueeFinish"
        case SELECT_MARQUEE_START = "selectMarqueeStart"
        case SIGNAL = "signal"
        case TREE_ITEM_CREATE = "treeItemCreate"
        case TREE_ITEM_MOVE = "treeItemMove"
        case TREE_ITEM_REMOVE = "treeItemRemove"
        case TREE_ITEM_UPDATE = "treeItemUpdate"
        case ZOOM = "zoom"
        case ZOOM_END = "zoomEnd"
        case ZOOM_START = "zoomStart"

        public func getJsBase() -> String {
            return "'\(self.rawValue)'"
        }

    }

}
